FROM node:20.11.0-bullseye@sha256:62c57336c7304cc4752cad1622431fb3c914e965fa9e35b3254c044cfe9e11d4 as builder

WORKDIR /app

LABEL org.opencontainers.image.vendor="Eduar avendaño <xavieravendano9@gmail.com" \
    org.opencontainers.image.description="Frontend del servicio IdeaBank"

COPY . .

EXPOSE 3000

CMD ["npm", "start"]