export const status = {
    PENDING: "PENDIENTE",
    APPROVED: "APROBADO",
    IN_PROGRESS: "EN PROGRESO",
    REFUSED: "RECHAZADO",
    DONE: "LISTO",
    PENDING_VALIDATION: "PENDIENTE DE VALIDAR"
};